=== Sonata6/Epam-traning/2nd_task/src/main/resources/data/BankAccountTable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/accounts"
        xmlns:tns="http://www.example.org/accounts"
        elementFormDefault="qualified">


    <!-- ROOT ELEMENT -->

    <element name="bank-accounts">
        <complexType>
            <sequence>
                <element ref="tns:account" minOccurs="0" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>


    <!-- CHILD ELEMENT OF ROOT -->

    <complexType name="account-type">
        <sequence>
            <element name="name" type="string"/>
            <element name="country" type="string"/>
            <element name="type" type="tns:Deposit-types"/>
            <element name="depositor" type="Name"/>
            <element name="account-id" type="tns:AccountId"/>
            <element name="amount-on-deposit" type="double"/>
            <element name="profitability" type="string"/>
            <element name="time-constraints" type="gYearMonth"/>
        </sequence>
        <attribute name="login" type="tns:Login" use="optional"/>
        <attribute name="world-top-number" type="tns:WorldTopNumber" use="required"/>
    </complexType>

    <complexType name="refillableAccount">
        <complexContent>
            <extension base="tns:account-type">
                <sequence>
                    <element name="monthly-accrual" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="nonRefillableAccount">
        <complexContent>
            <extension base="tns:account-type">
                <sequence>
                    <element name="intermediate-accrual" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="Name">
        <restriction base="string">
            <minLength value="2"/>
            <maxLength value="20"/>
        </restriction>
    </simpleType>

    <simpleType name="Login">
        <restriction base="ID">
            <pattern value="\w{1,16}"/>
        </restriction>
    </simpleType>

    <simpleType name="WorldTopNumber">
        <restriction base="int">
            <pattern value="\d{1,10}"/>
        </restriction>
    </simpleType>

    <simpleType name="AccountId">
        <restriction base="string">
        </restriction>
    </simpleType>


    <simpleType name="Deposit-types">
        <restriction base="string">
            <enumeration value="demand"/>
            <enumeration value="time"/>
            <enumeration value="settlement"/>
            <enumeration value="accumulative"/>
            <enumeration value="savings"/>
            <enumeration value="metal"/>
        </restriction>
    </simpleType>

    <element name="account" type="tns:account-type" abstract="true"/>
    <element name="refillable-account" type="tns:refillableAccount" substitutionGroup="tns:account"/>
    <element name="non-refillable-account" type="tns:nonRefillableAccount" substitutionGroup="tns:account"/>
</schema>

=== Sonata6/Epam-traning/2nd_task/src/main/resources/data/BankAccount.xml
<?xml version="1.0" encoding="UTF-8"?>
<bank-accounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.org/accounts"
         xsi:schemaLocation="http://www.example.org/accounts ../data/BankAccountTable.xsd">

    <refillable-account login="qwertyui" world-top-number="7"><!--1-->
        <name>Paribas</name>
        <country>France</country>
        <type>demand</type>
        <depositor>Bob</depositor>
        <account-id>40227810099910004312</account-id>
        <amount-on-deposit>3000</amount-on-deposit><!--in dollars-->
        <profitability>2.0</profitability><!--in percents-->
        <time-constraints>2023-06</time-constraints>
        <monthly-accrual>false</monthly-accrual>
    </refillable-account>

    <refillable-account login="qwertydi" world-top-number="8"><!--2-->
        <name>Citigroup</name>
        <country>USA</country>
        <type>time</type>
        <depositor>Lana</depositor>
        <account-id>40657810022810004312</account-id>
        <amount-on-deposit>2340</amount-on-deposit><!--in dollars-->
        <profitability>2.4</profitability><!--in percents-->
        <time-constraints>2023-05</time-constraints>
        <monthly-accrual>true</monthly-accrual>
    </refillable-account>

    <refillable-account login="qwfrtyui" world-top-number="9"><!--3-->
        <name>Japan Post Bank</name>
        <country>Japan</country>
        <type>settlement</type>
        <depositor>Andrew</depositor>
        <account-id>45417810099910004312</account-id>
        <amount-on-deposit>3123</amount-on-deposit><!--in dollars-->
        <profitability>2.3</profitability><!--in percents-->
        <time-constraints>2024-06</time-constraints>
        <monthly-accrual>false</monthly-accrual>
    </refillable-account>

    <refillable-account login="qgertyui" world-top-number="10"><!--4-->
        <name>Sumitomo Mitsui Financial Group</name>
        <country>Japan</country>
        <type>accumulative</type>
        <depositor>Alice</depositor>
        <account-id>46617810099910004312</account-id>
        <amount-on-deposit>335</amount-on-deposit><!--in dollars-->
        <profitability>2.1</profitability><!--in percents-->
        <time-constraints>2026-06</time-constraints>
        <monthly-accrual>false</monthly-accrual>
    </refillable-account>

    <refillable-account login="qwehtyui" world-top-number="11"><!--5-->
        <name>Mizuho Financial Group</name>
        <country>Japan</country>
        <type>savings</type>
        <depositor>Harry</depositor>
        <account-id>44817810099910004312</account-id>
        <amount-on-deposit>6000</amount-on-deposit><!--in dollars-->
        <profitability>4.5</profitability><!--in percents-->
        <time-constraints>2022-03</time-constraints>
        <monthly-accrual>true</monthly-accrual>
    </refillable-account>

    <refillable-account login="qwejtyui" world-top-number="12"><!--6-->
        <name>Banko Santander</name>
        <country>Spain</country>
        <type>metal</type>
        <depositor>Alexandr</depositor>
        <account-id>42817810099910004312</account-id>
        <amount-on-deposit>4323</amount-on-deposit><!--in dollars-->
        <profitability>2.7</profitability><!--in percents-->
        <time-constraints>2023-06</time-constraints>
        <monthly-accrual>false</monthly-accrual>
    </refillable-account>

    <refillable-account login="qkertyui" world-top-number="13"><!--7-->
        <name>Postal Savings Bank of China</name>
        <country>Britain</country>
        <type>demand</type>
        <depositor>Oliver</depositor>
        <account-id>40817810099918804312</account-id>
        <amount-on-deposit>4321</amount-on-deposit><!--in dollars-->
        <profitability>1.9</profitability><!--in percents-->
        <time-constraints>2023-08</time-constraints>
        <monthly-accrual>true</monthly-accrual>
    </refillable-account>

    <refillable-account login="qweltyui" world-top-number="14"><!--8-->
        <name>Societe Generale</name>
        <country>France</country>
        <type>time</type>
        <depositor>Jack</depositor>
        <account-id>40817810099912304312</account-id>
        <amount-on-deposit>4000</amount-on-deposit><!--in dollars-->
        <profitability>4.4</profitability><!--in percents-->
        <time-constraints>2023-01</time-constraints>
        <monthly-accrual>false</monthly-accrual>
    </refillable-account>

    <non-refillable-account login="qwzrtyui" world-top-number="15"><!--9-->
        <name>Deutsche Bank</name>
         <country>Germany</country>
        <type>accumulative</type>
        <depositor>Jacob</depositor>
        <account-id>40817810559910004312</account-id>
        <amount-on-deposit>5000</amount-on-deposit><!--in dollars-->
        <profitability>2.3</profitability><!--in percents-->
        <time-constraints>2025-11</time-constraints>
        <intermediate-accrual>true</intermediate-accrual>
    </non-refillable-account>

    <non-refillable-account login="qcertyui" world-top-number="16"><!--10-->
        <name>Groupe BPCE</name>
        <country>France</country>
        <type>settlement</type>
        <depositor>Charley</depositor>
        <account-id>40817810339910004312</account-id>
        <amount-on-deposit>3100</amount-on-deposit><!--in dollars-->
        <profitability>2.2</profitability><!--in percents-->
        <time-constraints>2021-06</time-constraints>
        <intermediate-accrual>false</intermediate-accrual>
    </non-refillable-account>

    <non-refillable-account login="qwextyui" world-top-number="0"><!--11-->
        <name>Industrial and Commercial Bank of China</name>
        <country>China</country>
        <type>savings</type>
        <depositor>Thomas</depositor>
        <account-id>40817810099650004312</account-id>
        <amount-on-deposit>3500</amount-on-deposit><!--in dollars-->
        <profitability>2.0</profitability><!--in percents-->
        <time-constraints>2023-12</time-constraints>
        <intermediate-accrual>false</intermediate-accrual>
    </non-refillable-account>

    <non-refillable-account login="qwervyui" world-top-number="1"><!--12-->
        <name>Agricultural Bank of China</name>
        <country>China</country>
        <type>metal</type>
        <depositor>George</depositor>
        <account-id>40834810099910004312</account-id>
        <amount-on-deposit>2600</amount-on-deposit><!--in dollars-->
        <profitability>3.5</profitability><!--in percents-->
        <time-constraints>2024-06</time-constraints>
        <intermediate-accrual>false</intermediate-accrual>
    </non-refillable-account>

    <non-refillable-account login="qwbrtyui" world-top-number="2"><!--13-->
        <name>Paribas</name>
        <country>France</country>
        <type>demand</type>
        <depositor>Oscar</depositor>
        <account-id>40817650099910004312</account-id>
        <amount-on-deposit>14400</amount-on-deposit><!--in dollars-->
        <profitability>3.0</profitability><!--in percents-->
        <time-constraints>2024-05</time-constraints>
        <intermediate-accrual>true</intermediate-accrual>
    </non-refillable-account>

    <non-refillable-account login="nwertyui" world-top-number="3"><!--14-->
        <name>China Construction Bank Corporation</name>
        <country>China</country>
        <type>time</type>
        <depositor>Daniel</depositor>
        <account-id>40845810099910004312</account-id>
        <amount-on-deposit>500</amount-on-deposit><!--in dollars-->
        <profitability>4.5</profitability><!--in percents-->
        <time-constraints>2024-04</time-constraints>
        <intermediate-accrual>false</intermediate-accrual>
    </non-refillable-account>

    <non-refillable-account login="qwmrtyui" world-top-number="4"><!--15-->
        <name>Bank of China ltd</name>
        <country>China</country>
        <type>settlement</type>
        <depositor>Bob</depositor>
        <account-id>40817810022910004312</account-id>
        <amount-on-deposit>5670</amount-on-deposit><!--in dollars-->
        <profitability>3.6</profitability><!--in percents-->
        <time-constraints>2024-03</time-constraints>
        <intermediate-accrual>true</intermediate-accrual>
    </non-refillable-account>

    <non-refillable-account login="qwertydf" world-top-number="5"><!--16-->
        <name>Bank of China ltd</name>
        <country>Japan</country>
        <type>time</type>
        <depositor>Logan</depositor>
        <account-id>40817810095410004312</account-id>
        <amount-on-deposit>3050</amount-on-deposit><!--in dollars-->
        <profitability>3.4</profitability><!--in percents-->
        <time-constraints>2024-02</time-constraints>
        <intermediate-accrual>true</intermediate-accrual>
    </non-refillable-account>

</bank-accounts>
